version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "3000:3000" # Reactのポート
      - "5000:5000" # Flaskのポート
